# Generated by Django 4.1 on 2023-05-14 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Admin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.CharField(max_length=256)),
                ("password", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Student",
            fields=[
                ("name", models.CharField(max_length=256)),
                (
                    "sid",
                    models.CharField(max_length=256, primary_key=True, serialize=False),
                ),
                ("password", models.CharField(max_length=256)),
                ("grade", models.CharField(max_length=256)),
                ("apartment", models.CharField(max_length=256)),
                ("major", models.CharField(max_length=256)),
                ("classes", models.CharField(max_length=256)),
                ("id", models.CharField(max_length=256)),
                ("stage", models.CharField(max_length=256)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="Teacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("tid", models.CharField(max_length=256)),
                ("password", models.CharField(max_length=256)),
                ("identity", models.CharField(max_length=256)),
                ("apartment", models.CharField(max_length=256)),
                ("phone", models.IntegerField()),
                ("email", models.EmailField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="TestBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                ("startTime", models.DateField()),
                ("endTime", models.DateField()),
                ("date", models.DateField()),
                ("state", models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name="TestClass",
            fields=[
                ("name", models.CharField(max_length=256)),
                ("id", models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name="TestRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("area", models.CharField(max_length=256)),
                ("MaxNum", models.IntegerField()),
                ("CurrentNum", models.IntegerField()),
                (
                    "test_batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.testbatch"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestTeacher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.testroom"
                    ),
                ),
                (
                    "test_teacher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.teacher"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TestStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "test_room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.testroom"
                    ),
                ),
                (
                    "test_student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.student"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="testbatch",
            name="test_class",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="main.testclass"
            ),
        ),
    ]
