# Generated by Django 4.1 on 2023-05-15 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="teststudent",
            name="photo",
            field=models.FileField(default="", upload_to="photo"),
            preserve_default=False,
        ),
    ]
