# Generated by Django 4.1 on 2023-05-16 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_score"),
    ]

    operations = [
        migrations.RemoveField(model_name="score", name="student",),
        migrations.RemoveField(model_name="score", name="test_room",),
        migrations.AddField(
            model_name="score",
            name="student_id",
            field=models.CharField(default="0", max_length=256),
        ),
        migrations.AddField(
            model_name="score",
            name="test_room_id",
            field=models.CharField(default="0", max_length=256),
        ),
    ]
