# Generated by Django 4.1 on 2023-05-22 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_remove_score_student_remove_score_test_room_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="testbatch",
            name="time",
            field=models.CharField(default="9:00", max_length=256),
        ),
    ]
