# Generated by Django 4.1 on 2023-05-23 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_testbatch_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="teststudent",
            name="pay",
            field=models.CharField(default="0", max_length=256),
        ),
    ]
